import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState, useEffect } from 'react'
import { For, Stack, Table } from "@chakra-ui/react"
import { format } from 'date-fns'

const API_PATH = "http://127.0.0.1:5328/api"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

enum FilterOp {
  eq = "Equals",
  neq = "Not Equals",
  lt = "Less than",
  lte = "Less than or equal to",
  gt = "Greater than",
  gte = "Greater than or equal to",
  none = ""
}

enum SortOrder {
  asc = "Ascending",
  desc = "Descending",
}

interface IVoterRegDataItem {
  state: string
  deadline_by_mail: Date | null
  deadline_in_person: Date | null
  deadline_online: Date | null
  election_day_registration: string
  online_registration_link: string
  description: string
}

export default function Home() {
  const [voterRegData, setVoterRegData] = useState<[IVoterRegDataItem] | []>([])
  const [filter_by, set_filter_by] = useState<string>("")
  const [filter_op, set_filter_op] = useState<FilterOp>(FilterOp.none)
  const [filter_value, set_filter_value] = useState<string>("")
  const [order_by, set_order_by] = useState<string>("")
  const [sort_order, set_sort_order] = useState<SortOrder>(SortOrder.asc)

  useEffect(() => {
    const params = {
      filter_by: filter_by,
      filter_op: filter_op,
      filter_value: filter_value,
      order_by: order_by,
      sort_order: sort_order
    }

    fetch(API_PATH, {
      body: new URLSearchParams(params)
    }).then(response => {
      console.log(response)
      return response.json()
    }).then(data => {
      setVoterRegData(data)
    }).catch(e => {
      console.error(e)
    })
  }, [filter_by, filter_op, filter_value, order_by, sort_order])

  return (
    <Table.Root>
      <Table.Caption />
      <Table.Header>
        <Table.Row>
          <Table.ColumnHeader>State</Table.ColumnHeader>
          <Table.ColumnHeader>Registration Deadline In-Person</Table.ColumnHeader>
          <Table.ColumnHeader>Registration Deadline By Mail	</Table.ColumnHeader>
          <Table.ColumnHeader>Registration Deadline Online	</Table.ColumnHeader>
          <Table.ColumnHeader>Election Day Registration</Table.ColumnHeader>
          <Table.ColumnHeader>Online Registration Link</Table.ColumnHeader>
          <Table.ColumnHeader>Description</Table.ColumnHeader>
        </Table.Row>
      </Table.Header>
      <Table.Body>
        {voterRegData.map((item: IVoterRegDataItem) => (
          <Table.Row key={item.state}>
            <Table.Cell>{item.state}</Table.Cell>
            <Table.Cell>{item.deadline_by_mail 
              ? format(item.deadline_by_mail, "YYYY-MM-DD")
              : ""
            }</Table.Cell>
            <Table.Cell>{item.deadline_in_person 
              ? format(item.deadline_in_person, "YYYY-MM-DD")
              : ""}</Table.Cell>
            <Table.Cell>{item.deadline_online 
              ? format(item.deadline_online, "YYYY-MM-DD")
              : ""}</Table.Cell>
            <Table.Cell>{item.election_day_registration}</Table.Cell>
            <Table.Cell>{item.online_registration_link}</Table.Cell>
            <Table.Cell>{item.description}</Table.Cell>
          </Table.Row>
        ))}
      </Table.Body>
    </Table.Root>
  )
}

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div
//         className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
//       >
//         <main className={styles.main}>
//           <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js logo"
//             width={100}
//             height={20}
//             priority
//           />
//           <div className={styles.intro}>
//             <h1>To get started, edit the index.tsx file.</h1>
//             <p>
//               Looking for a starting point or more instructions? Head over to{" "}
//               <a
//                 href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
//                 target="_blank"
//                 rel="noopener noreferrer"
//               >
//                 Templates
//               </a>{" "}
//               or the{" "}
//               <a
//                 href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
//                 target="_blank"
//                 rel="noopener noreferrer"
//               >
//                 Learning
//               </a>{" "}
//               center.
//             </p>
//           </div>
//           <div className={styles.ctas}>
//             <a
//               className={styles.primary}
//               href="https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               <Image
//                 className={styles.logo}
//                 src="/vercel.svg"
//                 alt="Vercel logomark"
//                 width={16}
//                 height={16}
//               />
//               Deploy Now
//             </a>
//             <a
//               className={styles.secondary}
//               href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               Documentation
//             </a>
//           </div>
//         </main>
//       </div>
//     </>
//   );
// }
